### ISSUE TITLE
Error polling ports module. Check log file for more details.

### ISSUE THREAD

**Issue by 72tlukas72** [librenms/docker#410]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/librenms/docker/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Hello,

I have problem on few device with error Error polling ports module. Check log file for more details.

Version	23.11.0

Looks like problem with (UTF-8/Win1250) coding?

### Expected behaviour

RRD works as usuall.

### Actual behaviour

Error messagess No Data file port, event log spam with Error polling ports module. Check log file for more details.

### Steps to reproduce

Add device with interface with UTF-8 characters

### Docker info

```text
Kernel Version: 5.15.0-78-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
```

### Logs

```text
Next Illuminate\Database\QueryException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xFDipoje...' for column `librenms`.`eventlog`.`message` at row 1 (Conne
ction: mysql, SQL: insert into `eventlog` (`reference`, `type`, `datetime`, `severity`, `message`, `username`, `device_id`) values (3632, interface, 2023-12-01 09:10:29, 3, ifName: P?ip
ojen? WAN Miniport (L2TP) -> P.ipojen. WAN Miniport (L2TP), , 118)) in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\Database\Connection->runQueryCallback()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->run()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\Database\Connection->statement()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3383): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1925): Illuminate\Database\Query\Builder->insertGetId()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1333): Illuminate\Database\Eloquent\Builder->__call()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1298): Illuminate\Database\Eloquent\Model->insertAndSetId()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1137): Illuminate\Database\Eloquent\Model->performInsert()
#9 /opt/librenms/app/Models/Eventlog.php(88): Illuminate\Database\Eloquent\Model->save()
#10 /opt/librenms/app/Models/Eventlog.php(58): App\Models\Eventlog->_log()
#11 /opt/librenms/includes/functions.php(238): App\Models\Eventlog::log()
#12 /opt/librenms/includes/polling/ports.inc.php(723): log_event()
#13 /opt/librenms/LibreNMS/Modules/LegacyModule.php(114): include('...')
#14 /opt/librenms/LibreNMS/Poller.php(176): LibreNMS\Modules\LegacyModule->poll()
#15 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#16 /opt/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#23 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#25 /opt/librenms/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#26 /opt/librenms/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#27 /opt/librenms/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#28 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#29 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#30 /opt/librenms/lnms(39): App\Console\Kernel->handle()
#31 {main}
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xFDipoje...' for column `librenms`.`eventlog`.`message` at row 1 (Connection: mysql, SQL: insert into `eventlog`
 (`reference`, `type`, `datetime`, `severity`, `message`, `username`, `device_id`) values (3632, interface, 2023-12-01 09:10:29, 3, ifName: P?ipojen? WAN Miniport (L2TP) -> P.ipojen. WA
N Miniport (L2TP), , 118)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFDipoje.
..' for column `librenms`.`eventlog`.`message` at row 1 (Connection: mysql, SQL: insert into `eventlog` (`reference`, `type`, `datetime`, `severity`, `message`, `username`, `device_id`)
 values (3632, interface, 2023-12-01 09:10:29, 3, ifName: P?ipojen? WAN Miniport (L2TP) -> P�ipojen� WAN Miniport (L2TP), , 118)) at /opt/librenms/vendor/laravel/framework/src/Illuminat
e/Database/Connection.php:795)
[previous exception] [object] (PDOException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFDipoje...' for column `librenms`.`eventlog`.`messag
e` at row 1 at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:580)"}
```

**Comment by murrant** [comment]
What is the output from snmpwalk?

**Comment by 72tlukas72** [comment]
[complete_snmpwalk.txt](https://github.com/librenms/docker/files/13527021/complete_snmpwalk.txt)

Complete debug SNMP log in attachment

**Comment by murrant** [comment]
@72tlukas72 Looks like snmpwalk is mangling the UTF-8 `.1.3.6.1.2.1.2.2.1.2.2 = STRING: P�ipojen� WAN Miniport (L2TP)`

Odd.

**Comment by murrant** [comment]
Even with that, when I tried to use your snmpwalk to simulate a device, I couldn't make it crash.
