### ISSUE TITLE
Cron: unable to launch a new process on Kubernetes

### ISSUE THREAD

**Issue by solune** [librenms/docker#57]
### Behaviour
randomly error in sidecar cron container: Unable to launch a new process

### Configuration

* run librenms in kubernetes

### Docker info

```
$ kubectl get nodes -o wide
NAME           STATUS   ROLES               AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION     CONTAINER-RUNTIME
10.35.20.201   Ready    worker              57m   v1.14.6   10.35.20.201   <none>        RancherOS v1.5.4   4.14.138-rancher   docker://18.6.1
```

### Logs

```
[2020-01-16 10:50:43] production.ERROR: Unable to launch a new process. {"exception":"[object] (Symfony\\Component\\Process\\Exception\\RuntimeException(code: 0): Unable to launch a new process. at /opt/librenms/vendor/symfony/process/Process.php:340)
[stacktrace]
#0 /opt/librenms/vendor/symfony/process/Process.php(234): Symfony\\Component\\Process\\Process->start(NULL, Array)
#1 /opt/librenms/includes/snmp.inc.php(365): Symfony\\Component\\Process\\Process->run()
#2 /opt/librenms/includes/functions.php(634): snmp_check(Array)
#3 /opt/librenms/includes/functions.php(2225): isSNMPable(Array)
#4 /opt/librenms/includes/polling/functions.inc.php(278): device_is_up(Array, true)
#5 /opt/librenms/poller.php(174): poll_device(Array, false)
#6 {main}
"}
Error in mempools module. The process has been signaled with signal "9".
#0 /opt/librenms/vendor/symfony/process/Process.php(236): Symfony\Component\Process\Process->wait()
#1 /opt/librenms/includes/common.php(119): Symfony\Component\Process\Process->run()
#2 /opt/librenms/includes/snmp.inc.php(382): external_exec(Array)
#3 /opt/librenms/includes/snmp.inc.php(460): snmp_walk(Array, 'hpGlobal', '-OQUs', 'NETSWITCH-MIB', 'hp')
#4 /opt/librenms/includes/polling/mempools/hpGlobal.inc.php(11): snmpwalk_cache_oid(Array, 'hpGlobal', NULL, 'NETSWITCH-MIB', 'hp')
#5 /opt/librenms/includes/polling/mempools.inc.php(13): include('/opt/librenms/i...')
#6 /opt/librenms/includes/polling/functions.inc.php(306): include('/opt/librenms/i...')
#7 /opt/librenms/poller.php(174): poll_device(Array, false)
#8 {main}

Error in ports module. Command failed: /usr/bin/rrdtool -
```

**Comment by crazy-max** [comment]
@solune Never tried to use LibreNMS on Kubernetes. Can you post your configuration? Maybe someone here can help you.

**Comment by solune** [comment]
I solved the problem, my memory limit of the container was too small.
Thanks
